
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_wangfuquan
    username: root
    password: 12103990203
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
